export const _arrOne = [
  "C",
  "r",
  "e",
  "a",
  "t",
  "i",
  "o",
  "n",
  " ",
  "o",
  "f",
  " ",
  "a",
  " ",
  "q",
  "u",
  "a",
  "l",
  "l",
  "i",
  "t",
  "y",
  " ",
  "p",
  "r",
  "o",
  "j",
  "e",
  "c",
  "t",
  ".",
  ".",
  ".",
];

export const _arrTwo = [
  "Web-DEV:~ ",
  "P",
  "r",
  "o",
  "j",
  "e",
  "c",
  "t",
  " ",
  "c",
  "o",
  "m",
  "p",
  "l",
  "i",
  "t",
  "e",
  "d",
];

export const _dataSlide = [
  "I tried to write an Instagram clone and implement all the main functions of this platform",
  "The typical pattern of an online pizza shop. All the functionality of orders, as well as authorization and registration is implemented",
  "Chat with special encryption and even more interesting functionality ",
  "It is not ready yet, but it will appear soon",
];

export const _dataDescriptionSlide = [
  "Written in React, the backend functionality is also made in react",
  "The project is implemented using the React framework and the back-end is implemented on node.js, mongo",
  "The project also is implemented using the React framework and the back-end is implemented on node.js, mongo ",
  "It is not ready yet, but it will appear soon.",
];

export const _nameProject = ["Instaclone", "Pizza", "Chat", "Task Manager"];
